### ISSUE TITLE
Use Zypak for sandboxing

### ISSUE THREAD

**Issue by rugk** [flathub/com.github.Eloston.UngoogledChromium#126]
Many Electron apps (based on the Chromium engine) use [Zypak](https://github.com/refi64/zypak) for sub-sandboxing. I did not yet fully understand how it works, but maybe linking https://github.com/flathub/com.vscodium.codium/issues/55 may help and you can see the links/linked implementation there.

Note I searched issues and code for Zypak and did not found it, so I assume it is not yet used here, though as for a browser, this may be the most important thing to sandbox (i.e. sandbox websites from each other).

**Comment by rany2** [comment]
Because we build Chromium from source, there is no need to rely on LD_PRELOAD tricks like Zypak. It's a lot simpler and less error prone to patch Chromium itself which we do in https://github.com/flathub/com.github.Eloston.UngoogledChromium/blob/master/patches/chromium/flatpak-Add-initial-sandbox-support.patch which I use from the Chromium flatpak.

Also Zypak does not work as well with non-Electron apps, so it doesn't necessarily provide any advantage and if anything provides you with every disadvantage. Simply look at Chromium based browsers that use Zypak instead of patching Chromium source like Brave and Chrome; many odd issues caused by Zypak. Just to be clear, its pretty good and works well enough in most cases but this works for all cases at least in my usage.

IMO Zypak should only be used for Electron apps.

**Comment by rugk** [comment]
Thanks a lot for the explanation, this makes sense! (And good night I guess based on your timezone… :wink: )
