### ISSUE TITLE
Ungoogled froze my computer, Fontconfig error

### ISSUE THREAD

**Issue by arteeh** [flathub/com.github.Eloston.UngoogledChromium#14]
I was browsing the web, several tabs open when my whole computer suddenly froze. I restarted, checked journalctl and found this as the very last message:

`com.github.Eloston.UngoogledChromium.desktop[3618]: Fontconfig error: Cannot load default config file: No such file: (null)`

I can't say for sure that Ungoogled was the cause of the crash, but to me this sounds like a Flatpak permission issue. I've used the flatpak for a long time on my laptop and never had issues. I installed it on my desktop yesterday on which the freeze just happened. I've had freezing issues in Linux on this computer in the past so I'm not sure if Ungoogled is the problem.

I'm using the latest version of everything, on Arch.

**Comment by rany2** [comment]
@refi64 Any idea about this?

**Comment by refi64** [comment]
I don't think this is an ungoogled-chromium issue.

Generally, full system freezes happen due to one of three things:

- OOM
- Kernel panic
- GPU hang

The only one that any individual app has control over is the first one, which would probably be an upstream issue if anything (but I've never really seen it before).

It might be useful to try and pinpoint a website you were on at the time of the hang, if I had to guess, it may have had e.g. embedded WebGL or done something to make your GPU driver get stuck.

As for the log message mentioned, IIRC it often appears and is probably unrelated.

**Comment by arteeh** [comment]
Threw windows on that computer so I won't be able to follow up with info, making this a dead end I think. Closing.
