### ISSUE TITLE
Browser unable to connect to the Internet after some time opened

### ISSUE THREAD

**Issue by x80486** [flathub/com.github.Eloston.UngoogledChromium#57]
I rarely restart the system. I've mostly use `Suspend`. I've noticed that this browser is unable to connect to the Internet after it's been used for some time, and mostly idle.

This is probably one of those things that only surfaces in my system, but I wanted to open up the issue, just in case that it's easy to track down, and probably fixed.

> I don't have any problems restarting the browser, and that always fixes the issue.

I'm under `Arch Linux`. The browser's version is `Version 100.0.4896.127 (Official Build, ungoogled-chromium) (64-bit)`.

**Comment by x80486** [comment]
OK, here is something else. Because I don't restart the browser frequently, but the system do get updated frequently, I've noticed now that the `About Chromium` window have the version I sent initially, but `flatpak list` has `googled-chromium com.github.Eloston.UngoogledChromium 101.0.4951.41 stable system` :man_shrugging:

**Comment by rany2** [comment]
@x80486 `flatpak kill com.github.Eloston.UngoogledChromium` and open it up again?

**Comment by gollum-z** [comment]
Hi,
I recently installed `com.github.Eloston.UngoogledChromium 114.0.5735.106` via Flatpak because the AppImage on my ubuntu 20.04 did not start with an error (_/lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.35' not found_).

Now I experience the same error as TO ( @x80486): the browser stops working with `net::ERR_NO_SUPPORTED_PROXIES` in the developer console. This happens after some minutes (I just tested with a YouTube video). I have no extensions installed.
